name: Test

on: 
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
